# GitHub Sponsors
github: [iamsigint]

# Ko-fi
ko_fi: iamsigint

# Patreon
patreon: erbium_blockchain

# Open Collective
open_collective: erbium-blockchain

# Custom sponsorship URLs
custom: ["https://www.paypal.me/iamsigint", "https://buymeacoffee.com/iamsigint"]
